##### Naive Bayes with Numerical Data

For numerical features, we cannot use frequency counts.

Instead, we assume that the data follows a Gaussian (Normal) distribution.

---

##### Gaussian Probability Density Function

$$
P(x \mid C_k) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left(-\frac{(x - \mu)^2}{2\sigma^2}\right)
$$

---

##### Parameters

- $$\mu$$ → mean of feature for class \( C_k \)  
- $$\sigma^2$$ → variance of feature for class \( C_k \)  

---

##### Final Naive Bayes Formula

$$
P(C_k \mid X) \propto P(C_k)\cdot \prod_{i=1}^{n} P(x_i \mid C_k)
$$

where:

$$
P(x_i \mid C_k) \text{ is computed using Gaussian distribution}$$

##### Dataset: Height, Weight, Gender

| Height | Weight | Gender |
|--------|--------|--------|
| 172    | 150    | M      |
| 180    | 170    | M      |
| 165    | 140    | M      |
| 190    | 200    | M      |
| 139    | 100    | F      |
| 145    | 120    | F      |
| 160    | 140    | F      |
| 172    | 150    | F      |

H = 185 , W= 170 , Gender=?

##### Gaussian Assumption in Naive Bayes

In Gaussian Naive Bayes, we assume that each feature is normally distributed within each class.

---

##### Formally

For a feature \( x \) and class \( C_k \):

$$
x \mid C_k \sim \mathcal{N}(\mu_k, \sigma_k^2)
$$

---

##### What this means

- Height for Males → follows one Gaussian distribution  
- Height for Females → follows another Gaussian distribution  

---

##### Example

- Male height → mean ≈ 176, variance ≈ some value  
- Female height → mean ≈ 154, variance ≈ some value  

Each class has its own distribution.

---

##### Key Insight

We are not assuming:

- All heights are Gaussian 

We are assuming:

- Heights **within each class** are Gaussian

##### Problem

Given:

- Height = 185  
- Weight = 170  

Predict:

$$
\text{Gender = ?}
$$

---

##### Step 1: Separate Data by Class

Male (M):

- Heights: 172, 180, 165, 190  
- Weights: 150, 170, 140, 200  

Female (F):

- Heights: 139, 145, 160, 172  
- Weights: 100, 120, 140, 150  

---

##### Step 2: Compute Mean and Variance

###### For M:

$$
\mu_H^M = 176.75, \quad \sigma_H^M \approx 9.2
$$

$$
\mu_W^M = 165, \quad \sigma_W^M \approx 22.9
$$

---

###### For F:

$$
\mu_H^F = 154, \quad \sigma_H^F \approx 14.5
$$

$$
\mu_W^F = 127.5, \quad \sigma_W^F \approx 22.2
$$

---

##### Step 3: Gaussian Formula

$$
P(x \mid C) = \frac{1}{\sqrt{2\pi\sigma^2}} 
\exp\left(-\frac{(x - \mu)^2}{2\sigma^2}\right)
$$

---

##### Step 4: Compute Likelihoods

###### For M:

- Height = 185 → close to mean (176.75) 
- Weight = 170 → close to mean (165)  

👉 High probability

---

###### For F:

- Height = 185 → far from mean (154) 
- Weight = 170 → far from mean (127.5)   

👉 Very low probability

---

##### Step 5: Compare

$$
P(M \mid X) > P(F \mid X)
$$

---

##### Final Prediction

$$
\text{Gender = M}
$$

## using sklearn

In [2]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [3]:
data = {
    'Height': [172,180,165,190,139,145,160,172],
    'Weight': [150,170,140,200,100,120,140,150],
    'Gender': ['M','M','M','M','F','F','F','F']
}

df = pd.DataFrame(data)
df

   Height  Weight Gender
0     172     150      M
1     180     170      M
2     165     140      M
3     190     200      M
4     139     100      F
5     145     120      F
6     160     140      F
7     172     150      F

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])  # M=1, F=0
df

   Height  Weight  Gender
0     172     150       1
1     180     170       1
2     165     140       1
3     190     200       1
4     139     100       0
5     145     120       0
6     160     140       0
7     172     150       0

In [5]:
X = df[['Height', 'Weight']]
y = df['Gender']

In [6]:
model = GaussianNB()
model.fit(X, y)

GaussianNB()

In [7]:
# Input: Height=185, Weight=170
test = pd.DataFrame([[185,170]], columns=['Height','Weight'])

prediction = model.predict(test)
print("Encoded Prediction:", prediction)

Encoded Prediction: [1]

In [8]:
print("Predicted Gender:", le.inverse_transform(prediction))

Predicted Gender: ['M']

##### Is the Gaussian Assumption Always Correct?

No, the assumption that features follow a Gaussian distribution may not always be true.

---

##### Why can it be wrong?

- Real-world data may be:
  - Skewed (not symmetric)
  - Multi-modal (multiple peaks)
  - Contain outliers
  - Not normally distributed

---

##### Example

Height data may look roughly normal, but:

- Income data → highly skewed  
- Age distribution → not always Gaussian  

---

##### Then why does Naive Bayes still work?

Even with incorrect assumptions:

- It estimates probabilities reasonably well  
- Decision boundaries are often still correct  
- Errors may cancel out across features  

---

##### Key Insight

Naive Bayes is a **good classifier**, even if it is a **bad probability estimator**.

---

##### Conclusion

- Assumption may be wrong 
- Model can still perform well

##### Checking Gaussian Assumption using Distribution Plots

Before applying Gaussian Naive Bayes, we can visualize the data distribution.

---

##### Why?

Gaussian Naive Bayes assumes:

$$
x \mid C_k \sim \mathcal{N}(\mu, \sigma^2)
$$

So we check if the feature approximately follows a normal distribution.

---

##### How to check?

Use distribution plots (distplot / histplot / kdeplot):

- Histogram → shape of data  
- KDE (Kernel Density) → smooth curve  

---

##### Goal

- Bell-shaped curve → suitable for GaussianNB 
- Skewed / irregular → assumption may be weak