# PIMA Diabetes Classification with Optuna + XGBoost

This notebook builds a binary classifier for diabetes prediction using the PIMA Indians dataset and tunes XGBoost hyperparameters with Optuna.

## What this notebook covers
- Data loading and preprocessing
- Train/validation/test split (60/20/20)
- Optuna-driven hyperparameter optimization with pruning
- Final model training and ROC-AUC evaluation

## Goal
Maximize validation ROC-AUC while keeping generalization on the test set as stable as possible.

In [1]:
import optuna
import xgboost as xgb
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [ ]:
# Load dataset

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
    'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

df = pd.read_csv(url, names=columns)

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
# data cleaning
cols_with_zero = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_zero] = df[cols_with_zero].replace(0, np.nan)

df.fillna(df.median(), inplace=True)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,125.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,29.0,125.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,125.0,30.4,0.315,23,0

In [ ]:
# Split data (60:20:20)

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_temp, X_test, y_temp, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_temp, y_temp, test_size=0.25, stratify=y_temp, random_state=42
)

In [6]:
def objective(trial):

    params = {
        "objective": "binary:logistic",
        "eval_metric": "logloss",
        "verbosity": 0,

        # Regularization
        "lambda": trial.suggest_float("lambda", 1e-8, 10.0, log=True),
        "alpha": trial.suggest_float("alpha", 1e-8, 10.0, log=True),

        # Tree structure
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "gamma": trial.suggest_float("gamma", 1e-8, 1.0, log=True),

        # Sampling
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),

        # Learning
        "eta": trial.suggest_float("eta", 0.01, 0.3),
    }

    dtrain = xgb.DMatrix(X_train, label=y_train)
    dvalid = xgb.DMatrix(X_valid, label=y_valid)

    pruning_callback = optuna.integration.XGBoostPruningCallback(
        trial, "validation-logloss"
    )

    model = xgb.train(
        params,
        dtrain,
        num_boost_round=300,
        evals=[(dvalid, "validation")],
        early_stopping_rounds=30,
        callbacks=[pruning_callback],
    )

    preds = model.predict(dvalid)
    return roc_auc_score(y_valid, preds)

In [7]:
study = optuna.create_study(
    direction="maximize",
    pruner=optuna.pruners.SuccessiveHalvingPruner()
)

study.optimize(objective, n_trials=50)

[I 2026-04-25 02:54:56,094] A new study created in memory with name: no-name-067c5b3b-6916-4437-9359-535a47fb7068

[0]	validation-logloss:0.64332
[1]	validation-logloss:0.63508
[2]	validation-logloss:0.62728
[3]	validation-logloss:0.62038
[4]	validation-logloss:0.61607
[5]	validation-logloss:0.61011
[6]	validation-logloss:0.60640
[7]	validation-logloss:0.59990
[8]	validation-logloss:0.59365
[9]	validation-logloss:0.58822
[10]	validation-logloss:0.58456
[11]	validation-logloss:0.57946
[12]	validation-logloss:0.57762
[13]	validation-logloss:0.57302
[14]	validation-logloss:0.57138
[15]	validation-logloss:0.56923
[16]	validation-logloss:0.56466
[17]	validation-logloss:0.56206
[18]	validation-logloss:0.55937
[19]	validation-logloss:0.55515
[20]	validation-logloss:0.55338
[21]	validation-logloss:0.55007
[22]	validation-logloss:0.54578
[23]	validation-logloss:0.54194
[24]	validation-logloss:0.53767
[25]	validation-logloss:0.53612
[26]	validation-logloss:0.53393
[27]	validation-logloss:0.53272
[28]	validation-logloss:0.52921
[29]	validation-logloss:0.52777
[30]	validation-logloss:0.52550
[31]	validation-logloss:0.52284
[32]	validation-logloss:0.52029
[33]	validation-logloss:0.51671
[34]	validation-logloss:0.51401
[35]	validation-logloss:0.51337
[36]	validation-logloss:0.51080
[37]	validation-logloss:0.50833
[38]	validation-logloss:0.50632
[39]	validation-logloss:0.50456
[40]	validation-logloss:0.50231
[41]	validation-logloss:0.50008
[42]	validation-logloss:0.49752
[43]	validation-logloss:0.49483
[44]	validation-logloss:0.49258
[45]	validation-logloss:0.49095
[46]	validation-logloss:0.48935
[47]	validation-logloss:0.48761
[48]	validation-logloss:0.48593
[49]	validation-logloss:0.48473
[50]	validation-logloss:0.48320
[51]	validation-logloss:0.48152
[52]	validation-logloss:0.47965
[53]	validation-logloss:0.47790
[54]	validation-logloss:0.47611
[55]	validation-logloss:0.47432
[56]	validation-logloss:0.47313
[57]	validation-logloss:0.47244
[58]	validation-logloss:0.47069
[59]	validation-logloss:0.46976
[60]	validation-logloss:0.46851
[61]	validation-logloss:0.46684
[62]	validation-logloss:0.46624
[63]	validation-logloss:0.46558
[64]	validation-logloss:0.46396
[65]	validation-logloss:0.46317
[66]	validation-logloss:0.46210
[67]	validation-logloss:0.46122
[68]	validation-logloss:0.45976
[69]	validation-logloss:0.45834
[70]	validation-logloss:0.45715
[71]	validation-logloss:0.45653
[72]	validation-logloss:0.45534
[73]	validation-logloss:0.45459
[74]	validation-logloss:0.45354
[75]	validation-logloss:0.45259
[76]	validation-logloss:0.45213
[77]	validation-logloss:0.45198
[78]	validation-logloss:0.45090
[79]	validation-logloss:0.45064
[80]	validation-logloss:0.44972
[81]	validation-logloss:0.44936
[82]	validation-logloss:0.44852
[83]	validation-logloss:0.44749
[84]	validation-logloss:0.44721
[85]	validation-logloss:0.44695
[86]	validation-logloss:0.44629
[87]	validation-logloss:0.44505
[88]	validation-logloss:0.44449
[89]	validation-logloss:0.44389
[90]	validation-logloss:0.44334
[91]	validation-logloss:0.44274
[92]	validation-logloss:0.44228
[93]	validation-logloss:0.44209
[94]	validation-logloss:0.44143
[95]	validation-logloss:0.44033
[96]	validation-logloss:0.43992
[97]	validation-logloss:0.43961
[98]	validation-logloss:0.43908
[99]	validation-logloss:0.43809
[100]	validation-logloss:0.43779
[101]	validation-logloss:0.43753
[102]	validation-logloss:0.43668
[103]	validation-logloss:0.43631
[104]	validation-logloss:0.43537
[105]	validation-logloss:0.43524
[106]	validation-logloss:0.43544
[107]	validation-logloss:0.43495
[108]	validation-logloss:0.43455
[109]	validation-logloss:0.43426
[110]	validation-logloss:0.43353
[111]	validation-logloss:0.43337
[112]	validation-logloss:0.43322
[113]	validation-logloss:0.43299
[114]	validation-logloss:0.43292
[115]	validation-logloss:0.43274
[116]	validation-logloss:0.43236
[117]	validation-logloss:0.43193
[118]	validation-logloss:0.43179
[119]	validation-logloss:0.43168
[120]	validation-logloss:0.43095
[121]	validation-logloss:0.43116
[122]	validation-logloss:0.43052
[123]	validation-logloss:0.43031
[124]	validation-logloss:0.43031
[125]	validation-logloss:0.43025
[126]	validation-logloss:0.43018
[127]	validation-logloss:0.43017
[128]	validation-logloss:0.43032
[129]	validation-logloss:0.43016
[130]	validation-logloss:0.42978
[131]	validation-logloss:0.42954
[132]	validation-logloss:0.42913
[133]	validation-logloss:0.42917
[134]	validation-logloss:0.42915
[135]	validation-logloss:0.42894
[136]	validation-logloss:0.42901
[137]	validation-logloss:0.42912
[138]	validation-logloss:0.42891
[139]	validation-logloss:0.42896
[140]	validation-logloss:0.42888
[141]	validation-logloss:0.42845
[142]	validation-logloss:0.42822
[143]	validation-logloss:0.42817
[144]	validation-logloss:0.42823
[145]	validation-logloss:0.42805
[146]	validation-logloss:0.42769
[147]	validation-logloss:0.42742
[148]	validation-logloss:0.42735
[149]	validation-logloss:0.42739
[150]	validation-logloss:0.42727
[151]	validation-logloss:0.42693
[152]	validation-logloss:0.42684
[153]	validation-logloss:0.42649
[154]	validation-logloss:0.42641
[155]	validation-logloss:0.42643
[156]	validation-logloss:0.42643
[157]	validation-logloss:0.42665
[158]	validation-logloss:0.42666
[159]	validation-logloss:0.42663
[160]	validation-logloss:0.42640
[161]	validation-logloss:0.42653
[162]	validation-logloss:0.42644
[163]	validation-logloss:0.42647
[164]	validation-logloss:0.42658
[165]	validation-logloss:0.42626
[166]	validation-logloss:0.42584
[167]	validation-logloss:0.42601
[168]	validation-logloss:0.42598
[169]	validation-logloss:0.42597
[170]	validation-logloss:0.42596
[171]	validation-logloss:0.42595
[172]	validation-logloss:0.42597
[173]	validation-logloss:0.42598
[174]	validation-logloss:0.42574
[175]	validation-logloss:0.42532
[176]	validation-logloss:0.42506
[177]	validation-logloss:0.42488
[178]	validation-logloss:0.42476
[179]	validation-logloss:0.42463
[180]	validation-logloss:0.42445
[181]	validation-logloss:0.42416
[182]	validation-logloss:0.42402
[183]	validation-logloss:0.42420
[184]	validation-logloss:0.42443
[185]	validation-logloss:0.42461
[186]	validation-logloss:0.42469
[187]	validation-logloss:0.42479
[188]	validation-logloss:0.42461
[189]	validation-logloss:0.42456
[190]	validation-logloss:0.42467
[191]	validation-logloss:0.42441
[192]	validation-logloss:0.42441
[193]	validation-logloss:0.42431
[194]	validation-logloss:0.42450
[195]	validation-logloss:0.42431
[196]	validation-logloss:0.42421
[197]	validation-logloss:0.42412
[198]	validation-logloss:0.42409
[199]	validation-logloss:0.42385
[200]	validation-logloss:0.42395
[201]	validation-logloss:0.42395
[202]	validation-logloss:0.42392
[203]	validation-logloss:0.42399
[204]	validation-logloss:0.42410
[205]	validation-logloss:0.42413
[206]	validation-logloss:0.42419
[207]	validation-logloss:0.42424
[208]	validation-logloss:0.42424
[209]	validation-logloss:0.42424
[210]	validation-logloss:0.42402
[211]	validation-logloss:0.42402
[212]	validation-logloss:0.42408
[213]	validation-logloss:0.42428
[214]	validation-logloss:0.42458
[215]	validation-logloss:0.42483
[216]	validation-logloss:0.42472
[217]	validation-logloss:0.42490
[218]	validation-logloss:0.42514
[219]	validation-logloss:0.42513
[220]	validation-logloss:0.42528
[221]	validation-logloss:0.42528
[222]	validation-logloss:0.42528
[223]	validation-logloss:0.42543
[224]	validation-logloss:0.42541
[225]	validation-logloss:0.42528
[226]	validation-logloss:0.42546
[227]	validation-logloss:0.42555
[228]	validation-logloss:0.42539
[229]	validation-logloss:0.42512

[I 2026-04-25 02:54:56,528] Trial 0 finished with value: 0.8694444444444444 and parameters: {'lambda': 0.06166849926934415, 'alpha': 2.0426727582736115, 'max_depth': 3, 'min_child_weight': 2, 'gamma': 0.3398611605047213, 'subsample': 0.9749975371934416, 'colsample_bytree': 0.664727661100575, 'eta': 0.02674045739391727}. Best is trial 0 with value: 0.8694444444444444.

[0]	validation-logloss:0.61528
[1]	validation-logloss:0.54478
[2]	validation-logloss:0.50917
[3]	validation-logloss:0.48718
[4]	validation-logloss:0.47404
[5]	validation-logloss:0.46759
[6]	validation-logloss:0.46302
[7]	validation-logloss:0.45242
[8]	validation-logloss:0.45273
[9]	validation-logloss:0.45103
[10]	validation-logloss:0.44749
[11]	validation-logloss:0.45579
[12]	validation-logloss:0.46062
[13]	validation-logloss:0.46520
[14]	validation-logloss:0.46978
[15]	validation-logloss:0.47877
[16]	validation-logloss:0.48186
[17]	validation-logloss:0.48495
[18]	validation-logloss:0.48792
[19]	validation-logloss:0.49103
[20]	validation-logloss:0.49330
[21]	validation-logloss:0.49434
[22]	validation-logloss:0.49425
[23]	validation-logloss:0.49854
[24]	validation-logloss:0.49334
[25]	validation-logloss:0.49681
[26]	validation-logloss:0.49935
[27]	validation-logloss:0.49884
[28]	validation-logloss:0.50060
[29]	validation-logloss:0.50060
[30]	validation-logloss:0.49878
[31]	validation-logloss:0.50294
[32]	validation-logloss:0.50617
[33]	validation-logloss:0.50467
[34]	validation-logloss:0.50099
[35]	validation-logloss:0.50175
[36]	validation-logloss:0.50619
[37]	validation-logloss:0.50569
[38]	validation-logloss:0.50646
[39]	validation-logloss:0.50977
[40]	validation-logloss:0.51515

[I 2026-04-25 02:54:56,632] Trial 1 finished with value: 0.8185185185185185 and parameters: {'lambda': 1.8196214548446498e-06, 'alpha': 0.0008474436793876865, 'max_depth': 9, 'min_child_weight': 5, 'gamma': 0.004173612661299177, 'subsample': 0.9946833679417597, 'colsample_bytree': 0.6336929595337979, 'eta': 0.2810539370282118}. Best is trial 0 with value: 0.8694444444444444.

[0]	validation-logloss:0.64398
[1]	validation-logloss:0.63452
[2]	validation-logloss:0.63018
[3]	validation-logloss:0.62261
[4]	validation-logloss:0.61805
[5]	validation-logloss:0.61172
[6]	validation-logloss:0.60738
[7]	validation-logloss:0.59992
[8]	validation-logloss:0.59351
[9]	validation-logloss:0.58684
[10]	validation-logloss:0.58382
[11]	validation-logloss:0.58107
[12]	validation-logloss:0.57853
[13]	validation-logloss:0.57356
[14]	validation-logloss:0.57081
[15]	validation-logloss:0.56842
[16]	validation-logloss:0.56341
[17]	validation-logloss:0.56077
[18]	validation-logloss:0.55836
[19]	validation-logloss:0.55634
[20]	validation-logloss:0.55535
[21]	validation-logloss:0.55371
[22]	validation-logloss:0.55004
[23]	validation-logloss:0.54544
[24]	validation-logloss:0.54169
[25]	validation-logloss:0.54010
[26]	validation-logloss:0.53818
[27]	validation-logloss:0.53636
[28]	validation-logloss:0.53330
[29]	validation-logloss:0.52941
[30]	validation-logloss:0.52819
[31]	validation-logloss:0.52465
[32]	validation-logloss:0.52414
[33]	validation-logloss:0.51876
[34]	validation-logloss:0.51512
[35]	validation-logloss:0.51447
[36]	validation-logloss:0.51182
[37]	validation-logloss:0.50942
[38]	validation-logloss:0.50637
[39]	validation-logloss:0.50520
[40]	validation-logloss:0.50279
[41]	validation-logloss:0.50002
[42]	validation-logloss:0.49696
[43]	validation-logloss:0.49397
[44]	validation-logloss:0.49194
[45]	validation-logloss:0.49168
[46]	validation-logloss:0.48892
[47]	validation-logloss:0.48688
[48]	validation-logloss:0.48391
[49]	validation-logloss:0.48243
[50]	validation-logloss:0.48167
[51]	validation-logloss:0.47996
[52]	validation-logloss:0.47854
[53]	validation-logloss:0.47684
[54]	validation-logloss:0.47515
[55]	validation-logloss:0.47282
[56]	validation-logloss:0.47174
[57]	validation-logloss:0.47017
[58]	validation-logloss:0.46958
[59]	validation-logloss:0.46787
[60]	validation-logloss:0.46783
[61]	validation-logloss:0.46643
[62]	validation-logloss:0.46569
[63]	validation-logloss:0.46378
[64]	validation-logloss:0.46251
[65]	validation-logloss:0.46218
[66]	validation-logloss:0.46095
[67]	validation-logloss:0.45980
[68]	validation-logloss:0.45840
[69]	validation-logloss:0.45716
[70]	validation-logloss:0.45663
[71]	validation-logloss:0.45604
[72]	validation-logloss:0.45461
[73]	validation-logloss:0.45389
[74]	validation-logloss:0.45373
[75]	validation-logloss:0.45238
[76]	validation-logloss:0.45195
[77]	validation-logloss:0.45193
[78]	validation-logloss:0.45146
[79]	validation-logloss:0.45092
[80]	validation-logloss:0.45094
[81]	validation-logloss:0.45025
[82]	validation-logloss:0.44979
[83]	validation-logloss:0.44941
[84]	validation-logloss:0.44852
[85]	validation-logloss:0.44815
[86]	validation-logloss:0.44710
[87]	validation-logloss:0.44640
[88]	validation-logloss:0.44560
[89]	validation-logloss:0.44448
[90]	validation-logloss:0.44335
[91]	validation-logloss:0.44217
[92]	validation-logloss:0.44178
[93]	validation-logloss:0.44198
[94]	validation-logloss:0.44168
[95]	validation-logloss:0.44104
[96]	validation-logloss:0.44043
[97]	validation-logloss:0.44001
[98]	validation-logloss:0.43964
[99]	validation-logloss:0.43917
[100]	validation-logloss:0.43863
[101]	validation-logloss:0.43880
[102]	validation-logloss:0.43894
[103]	validation-logloss:0.43923
[104]	validation-logloss:0.43876
[105]	validation-logloss:0.43869
[106]	validation-logloss:0.43804
[107]	validation-logloss:0.43710
[108]	validation-logloss:0.43699
[109]	validation-logloss:0.43701
[110]	validation-logloss:0.43673
[111]	validation-logloss:0.43631
[112]	validation-logloss:0.43554
[113]	validation-logloss:0.43584
[114]	validation-logloss:0.43513
[115]	validation-logloss:0.43488
[116]	validation-logloss:0.43434
[117]	validation-logloss:0.43393
[118]	validation-logloss:0.43360
[119]	validation-logloss:0.43308
[120]	validation-logloss:0.43206
[121]	validation-logloss:0.43200
[122]	validation-logloss:0.43194
[123]	validation-logloss:0.43165
[124]	validation-logloss:0.43151
[125]	validation-logloss:0.43111
[126]	validation-logloss:0.43105
[127]	validation-logloss:0.43089
[128]	validation-logloss:0.43025
[129]	validation-logloss:0.43035
[130]	validation-logloss:0.43023
[131]	validation-logloss:0.42990
[132]	validation-logloss:0.42978
[133]	validation-logloss:0.43011
[134]	validation-logloss:0.43067
[135]	validation-logloss:0.43086
[136]	validation-logloss:0.43088
[137]	validation-logloss:0.43028
[138]	validation-logloss:0.43030
[139]	validation-logloss:0.43014
[140]	validation-logloss:0.43016
[141]	validation-logloss:0.42972
[142]	validation-logloss:0.42996
[143]	validation-logloss:0.43031
[144]	validation-logloss:0.43031
[145]	validation-logloss:0.43018
[146]	validation-logloss:0.43021
[147]	validation-logloss:0.43021
[148]	validation-logloss:0.42985
[149]	validation-logloss:0.42975
[150]	validation-logloss:0.43000
[151]	validation-logloss:0.43041
[152]	validation-logloss:0.43037
[153]	validation-logloss:0.43033
[154]	validation-logloss:0.43054
[155]	validation-logloss:0.43058
[156]	validation-logloss:0.43049
[157]	validation-logloss:0.43092
[158]	validation-logloss:0.43079
[159]	validation-logloss:0.43091
[160]	validation-logloss:0.43165
[161]	validation-logloss:0.43136
[162]	validation-logloss:0.43107
[163]	validation-logloss:0.43094
[164]	validation-logloss:0.43102
[165]	validation-logloss:0.43080
[166]	validation-logloss:0.43038
[167]	validation-logloss:0.43091
[168]	validation-logloss:0.43075
[169]	validation-logloss:0.43034
[170]	validation-logloss:0.43004
[171]	validation-logloss:0.42982

[I 2026-04-25 02:54:56,960] Trial 2 finished with value: 0.8683333333333334 and parameters: {'lambda': 5.741123924505133e-06, 'alpha': 0.00019240267879205915, 'max_depth': 9, 'min_child_weight': 8, 'gamma': 0.006683537622010966, 'subsample': 0.6324993985909391, 'colsample_bytree': 0.5031364048527044, 'eta': 0.026743094826252034}. Best is trial 0 with value: 0.8694444444444444.

[0]	validation-logloss:0.63818
[1]	validation-logloss:0.61188

[I 2026-04-25 02:54:56,975] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63061
[1]	validation-logloss:0.60720

[I 2026-04-25 02:54:56,993] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.62666
[1]	validation-logloss:0.57965

[I 2026-04-25 02:54:57,010] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64525
[1]	validation-logloss:0.64055
[2]	validation-logloss:0.63804
[3]	validation-logloss:0.63412
[4]	validation-logloss:0.63185
[5]	validation-logloss:0.62893
[6]	validation-logloss:0.62586
[7]	validation-logloss:0.62135
[8]	validation-logloss:0.61714
[9]	validation-logloss:0.61272
[10]	validation-logloss:0.61132
[11]	validation-logloss:0.60889
[12]	validation-logloss:0.60674
[13]	validation-logloss:0.60385
[14]	validation-logloss:0.60284
[15]	validation-logloss:0.60115
[16]	validation-logloss:0.59723
[17]	validation-logloss:0.59601
[18]	validation-logloss:0.59442
[19]	validation-logloss:0.59287
[20]	validation-logloss:0.59150
[21]	validation-logloss:0.58994
[22]	validation-logloss:0.58708
[23]	validation-logloss:0.58369
[24]	validation-logloss:0.58141
[25]	validation-logloss:0.57973
[26]	validation-logloss:0.57837
[27]	validation-logloss:0.57728
[28]	validation-logloss:0.57467
[29]	validation-logloss:0.57265
[30]	validation-logloss:0.57081
[31]	validation-logloss:0.56841
[32]	validation-logloss:0.56753
[33]	validation-logloss:0.56485
[34]	validation-logloss:0.56199
[35]	validation-logloss:0.56068
[36]	validation-logloss:0.55822
[37]	validation-logloss:0.55597
[38]	validation-logloss:0.55326
[39]	validation-logloss:0.55207
[40]	validation-logloss:0.54954
[41]	validation-logloss:0.54763
[42]	validation-logloss:0.54509
[43]	validation-logloss:0.54282
[44]	validation-logloss:0.54063
[45]	validation-logloss:0.54015
[46]	validation-logloss:0.53818
[47]	validation-logloss:0.53590
[48]	validation-logloss:0.53408
[49]	validation-logloss:0.53242
[50]	validation-logloss:0.53202
[51]	validation-logloss:0.53130
[52]	validation-logloss:0.53040
[53]	validation-logloss:0.52878
[54]	validation-logloss:0.52767
[55]	validation-logloss:0.52583
[56]	validation-logloss:0.52409
[57]	validation-logloss:0.52268
[58]	validation-logloss:0.52247
[59]	validation-logloss:0.52078
[60]	validation-logloss:0.52048
[61]	validation-logloss:0.51947
[62]	validation-logloss:0.51828
[63]	validation-logloss:0.51720
[64]	validation-logloss:0.51570
[65]	validation-logloss:0.51482
[66]	validation-logloss:0.51325
[67]	validation-logloss:0.51227
[68]	validation-logloss:0.51132
[69]	validation-logloss:0.50970
[70]	validation-logloss:0.50796
[71]	validation-logloss:0.50709
[72]	validation-logloss:0.50567
[73]	validation-logloss:0.50433
[74]	validation-logloss:0.50383
[75]	validation-logloss:0.50226
[76]	validation-logloss:0.50159
[77]	validation-logloss:0.50098
[78]	validation-logloss:0.50000
[79]	validation-logloss:0.49946
[80]	validation-logloss:0.49918
[81]	validation-logloss:0.49837
[82]	validation-logloss:0.49766
[83]	validation-logloss:0.49699
[84]	validation-logloss:0.49616
[85]	validation-logloss:0.49565
[86]	validation-logloss:0.49496
[87]	validation-logloss:0.49384
[88]	validation-logloss:0.49304
[89]	validation-logloss:0.49188
[90]	validation-logloss:0.49091
[91]	validation-logloss:0.49019
[92]	validation-logloss:0.48906
[93]	validation-logloss:0.48883
[94]	validation-logloss:0.48811
[95]	validation-logloss:0.48662
[96]	validation-logloss:0.48592
[97]	validation-logloss:0.48463
[98]	validation-logloss:0.48404
[99]	validation-logloss:0.48292
[100]	validation-logloss:0.48224
[101]	validation-logloss:0.48179
[102]	validation-logloss:0.48180
[103]	validation-logloss:0.48108
[104]	validation-logloss:0.48027
[105]	validation-logloss:0.47984
[106]	validation-logloss:0.47898
[107]	validation-logloss:0.47810
[108]	validation-logloss:0.47715
[109]	validation-logloss:0.47669
[110]	validation-logloss:0.47608
[111]	validation-logloss:0.47552
[112]	validation-logloss:0.47460
[113]	validation-logloss:0.47449
[114]	validation-logloss:0.47412
[115]	validation-logloss:0.47349
[116]	validation-logloss:0.47259
[117]	validation-logloss:0.47204
[118]	validation-logloss:0.47109
[119]	validation-logloss:0.46992
[120]	validation-logloss:0.46892
[121]	validation-logloss:0.46837
[122]	validation-logloss:0.46756
[123]	validation-logloss:0.46704
[124]	validation-logloss:0.46723
[125]	validation-logloss:0.46651
[126]	validation-logloss:0.46632
[127]	validation-logloss:0.46599
[128]	validation-logloss:0.46546
[129]	validation-logloss:0.46523
[130]	validation-logloss:0.46493
[131]	validation-logloss:0.46527
[132]	validation-logloss:0.46514
[133]	validation-logloss:0.46459
[134]	validation-logloss:0.46401
[135]	validation-logloss:0.46407
[136]	validation-logloss:0.46396
[137]	validation-logloss:0.46353
[138]	validation-logloss:0.46317
[139]	validation-logloss:0.46301
[140]	validation-logloss:0.46242
[141]	validation-logloss:0.46170
[142]	validation-logloss:0.46134
[143]	validation-logloss:0.46129
[144]	validation-logloss:0.46150
[145]	validation-logloss:0.46059
[146]	validation-logloss:0.45995
[147]	validation-logloss:0.45951
[148]	validation-logloss:0.45889
[149]	validation-logloss:0.45911
[150]	validation-logloss:0.45906
[151]	validation-logloss:0.45875
[152]	validation-logloss:0.45815
[153]	validation-logloss:0.45736
[154]	validation-logloss:0.45697
[155]	validation-logloss:0.45634
[156]	validation-logloss:0.45586
[157]	validation-logloss:0.45518
[158]	validation-logloss:0.45482
[159]	validation-logloss:0.45477
[160]	validation-logloss:0.45450
[161]	validation-logloss:0.45456
[162]	validation-logloss:0.45409
[163]	validation-logloss:0.45388
[164]	validation-logloss:0.45367
[165]	validation-logloss:0.45307
[166]	validation-logloss:0.45242
[167]	validation-logloss:0.45270
[168]	validation-logloss:0.45233
[169]	validation-logloss:0.45197
[170]	validation-logloss:0.45176
[171]	validation-logloss:0.45119
[172]	validation-logloss:0.45048
[173]	validation-logloss:0.44987
[174]	validation-logloss:0.44964
[175]	validation-logloss:0.44939
[176]	validation-logloss:0.44931
[177]	validation-logloss:0.44888
[178]	validation-logloss:0.44879
[179]	validation-logloss:0.44877
[180]	validation-logloss:0.44843
[181]	validation-logloss:0.44807
[182]	validation-logloss:0.44794
[183]	validation-logloss:0.44705
[184]	validation-logloss:0.44634
[185]	validation-logloss:0.44610
[186]	validation-logloss:0.44592
[187]	validation-logloss:0.44551
[188]	validation-logloss:0.44515
[189]	validation-logloss:0.44575
[190]	validation-logloss:0.44561
[191]	validation-logloss:0.44499
[192]	validation-logloss:0.44470
[193]	validation-logloss:0.44385
[194]	validation-logloss:0.44377
[195]	validation-logloss:0.44371
[196]	validation-logloss:0.44333
[197]	validation-logloss:0.44327
[198]	validation-logloss:0.44343
[199]	validation-logloss:0.44331
[200]	validation-logloss:0.44320
[201]	validation-logloss:0.44298
[202]	validation-logloss:0.44295
[203]	validation-logloss:0.44295
[204]	validation-logloss:0.44268
[205]	validation-logloss:0.44213
[206]	validation-logloss:0.44210
[207]	validation-logloss:0.44198
[208]	validation-logloss:0.44207
[209]	validation-logloss:0.44222
[210]	validation-logloss:0.44211
[211]	validation-logloss:0.44205
[212]	validation-logloss:0.44215
[213]	validation-logloss:0.44188
[214]	validation-logloss:0.44176
[215]	validation-logloss:0.44169
[216]	validation-logloss:0.44109
[217]	validation-logloss:0.44108
[218]	validation-logloss:0.44102
[219]	validation-logloss:0.44049
[220]	validation-logloss:0.44038
[221]	validation-logloss:0.44023
[222]	validation-logloss:0.44003
[223]	validation-logloss:0.44014
[224]	validation-logloss:0.44033
[225]	validation-logloss:0.44008
[226]	validation-logloss:0.44000
[227]	validation-logloss:0.43987
[228]	validation-logloss:0.43976
[229]	validation-logloss:0.43968
[230]	validation-logloss:0.43925
[231]	validation-logloss:0.43885
[232]	validation-logloss:0.43903
[233]	validation-logloss:0.43883
[234]	validation-logloss:0.43881
[235]	validation-logloss:0.43873
[236]	validation-logloss:0.43868
[237]	validation-logloss:0.43849
[238]	validation-logloss:0.43854
[239]	validation-logloss:0.43855
[240]	validation-logloss:0.43827
[241]	validation-logloss:0.43851
[242]	validation-logloss:0.43826
[243]	validation-logloss:0.43766
[244]	validation-logloss:0.43730
[245]	validation-logloss:0.43727
[246]	validation-logloss:0.43763
[247]	validation-logloss:0.43716
[248]	validation-logloss:0.43751
[249]	validation-logloss:0.43773
[250]	validation-logloss:0.43742
[251]	validation-logloss:0.43731
[252]	validation-logloss:0.43699
[253]	validation-logloss:0.43691
[254]	validation-logloss:0.43669
[255]	validation-logloss:0.43715
[256]	validation-logloss:0.43686
[257]	validation-logloss:0.43651
[258]	validation-logloss:0.43611
[259]	validation-logloss:0.43601
[260]	validation-logloss:0.43617
[261]	validation-logloss:0.43635
[262]	validation-logloss:0.43630
[263]	validation-logloss:0.43611
[264]	validation-logloss:0.43587
[265]	validation-logloss:0.43574
[266]	validation-logloss:0.43552
[267]	validation-logloss:0.43579
[268]	validation-logloss:0.43583
[269]	validation-logloss:0.43622
[270]	validation-logloss:0.43590
[271]	validation-logloss:0.43591
[272]	validation-logloss:0.43601
[273]	validation-logloss:0.43613
[274]	validation-logloss:0.43641
[275]	validation-logloss:0.43612
[276]	validation-logloss:0.43592
[277]	validation-logloss:0.43596
[278]	validation-logloss:0.43599
[279]	validation-logloss:0.43515
[280]	validation-logloss:0.43537
[281]	validation-logloss:0.43559
[282]	validation-logloss:0.43582
[283]	validation-logloss:0.43573
[284]	validation-logloss:0.43537
[285]	validation-logloss:0.43551
[286]	validation-logloss:0.43530
[287]	validation-logloss:0.43531
[288]	validation-logloss:0.43491
[289]	validation-logloss:0.43499
[290]	validation-logloss:0.43488
[291]	validation-logloss:0.43453
[292]	validation-logloss:0.43422
[293]	validation-logloss:0.43422
[294]	validation-logloss:0.43465
[295]	validation-logloss:0.43429
[296]	validation-logloss:0.43424
[297]	validation-logloss:0.43437
[298]	validation-logloss:0.43414
[299]	validation-logloss:0.43418

[I 2026-04-25 02:54:57,701] Trial 6 finished with value: 0.8696296296296295 and parameters: {'lambda': 4.321228963536233e-07, 'alpha': 0.0002237742348738362, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 1.1195756351090675e-08, 'subsample': 0.561556149437213, 'colsample_bytree': 0.5676139159388394, 'eta': 0.013915542743618298}. Best is trial 6 with value: 0.8696296296296295.

[0]	validation-logloss:0.64653
[1]	validation-logloss:0.64319
[2]	validation-logloss:0.64149
[3]	validation-logloss:0.63834
[4]	validation-logloss:0.63654
[5]	validation-logloss:0.63370
[6]	validation-logloss:0.63162
[7]	validation-logloss:0.62852
[8]	validation-logloss:0.62536
[9]	validation-logloss:0.62264
[10]	validation-logloss:0.62118
[11]	validation-logloss:0.61929
[12]	validation-logloss:0.61893
[13]	validation-logloss:0.61653
[14]	validation-logloss:0.61538
[15]	validation-logloss:0.61416
[16]	validation-logloss:0.61156
[17]	validation-logloss:0.61062
[18]	validation-logloss:0.60927
[19]	validation-logloss:0.60872
[20]	validation-logloss:0.60798
[21]	validation-logloss:0.60688
[22]	validation-logloss:0.60433
[23]	validation-logloss:0.60208
[24]	validation-logloss:0.59962
[25]	validation-logloss:0.59880
[26]	validation-logloss:0.59835
[27]	validation-logloss:0.59721
[28]	validation-logloss:0.59482
[29]	validation-logloss:0.59319
[30]	validation-logloss:0.59159
[31]	validation-logloss:0.58959
[32]	validation-logloss:0.58902
[33]	validation-logloss:0.58686
[34]	validation-logloss:0.58514
[35]	validation-logloss:0.58387
[36]	validation-logloss:0.58146
[37]	validation-logloss:0.57971
[38]	validation-logloss:0.57778
[39]	validation-logloss:0.57715
[40]	validation-logloss:0.57521
[41]	validation-logloss:0.57285
[42]	validation-logloss:0.57127
[43]	validation-logloss:0.56917
[44]	validation-logloss:0.56735
[45]	validation-logloss:0.56729
[46]	validation-logloss:0.56538
[47]	validation-logloss:0.56342
[48]	validation-logloss:0.56133
[49]	validation-logloss:0.55946
[50]	validation-logloss:0.55894
[51]	validation-logloss:0.55828
[52]	validation-logloss:0.55752
[53]	validation-logloss:0.55626
[54]	validation-logloss:0.55565
[55]	validation-logloss:0.55386
[56]	validation-logloss:0.55226
[57]	validation-logloss:0.55144
[58]	validation-logloss:0.55078
[59]	validation-logloss:0.54965
[60]	validation-logloss:0.54911
[61]	validation-logloss:0.54757
[62]	validation-logloss:0.54665
[63]	validation-logloss:0.54567
[64]	validation-logloss:0.54425
[65]	validation-logloss:0.54358
[66]	validation-logloss:0.54182
[67]	validation-logloss:0.54106
[68]	validation-logloss:0.53932
[69]	validation-logloss:0.53778
[70]	validation-logloss:0.53653
[71]	validation-logloss:0.53557
[72]	validation-logloss:0.53423
[73]	validation-logloss:0.53339
[74]	validation-logloss:0.53258
[75]	validation-logloss:0.53098
[76]	validation-logloss:0.53040
[77]	validation-logloss:0.52990
[78]	validation-logloss:0.52893
[79]	validation-logloss:0.52806
[80]	validation-logloss:0.52813
[81]	validation-logloss:0.52744
[82]	validation-logloss:0.52652
[83]	validation-logloss:0.52571
[84]	validation-logloss:0.52531
[85]	validation-logloss:0.52463
[86]	validation-logloss:0.52389
[87]	validation-logloss:0.52290
[88]	validation-logloss:0.52196
[89]	validation-logloss:0.52115
[90]	validation-logloss:0.51991
[91]	validation-logloss:0.51910
[92]	validation-logloss:0.51774
[93]	validation-logloss:0.51711
[94]	validation-logloss:0.51572
[95]	validation-logloss:0.51536
[96]	validation-logloss:0.51450
[97]	validation-logloss:0.51338
[98]	validation-logloss:0.51274
[99]	validation-logloss:0.51159
[100]	validation-logloss:0.51042
[101]	validation-logloss:0.50923
[102]	validation-logloss:0.50849
[103]	validation-logloss:0.50804
[104]	validation-logloss:0.50719
[105]	validation-logloss:0.50692
[106]	validation-logloss:0.50599
[107]	validation-logloss:0.50554
[108]	validation-logloss:0.50462
[109]	validation-logloss:0.50428
[110]	validation-logloss:0.50299
[111]	validation-logloss:0.50198
[112]	validation-logloss:0.50099
[113]	validation-logloss:0.50073
[114]	validation-logloss:0.49948
[115]	validation-logloss:0.49900
[116]	validation-logloss:0.49815
[117]	validation-logloss:0.49805
[118]	validation-logloss:0.49739
[119]	validation-logloss:0.49628
[120]	validation-logloss:0.49552
[121]	validation-logloss:0.49519
[122]	validation-logloss:0.49445
[123]	validation-logloss:0.49414
[124]	validation-logloss:0.49348
[125]	validation-logloss:0.49282
[126]	validation-logloss:0.49228
[127]	validation-logloss:0.49150
[128]	validation-logloss:0.49096
[129]	validation-logloss:0.49061
[130]	validation-logloss:0.49032
[131]	validation-logloss:0.49034
[132]	validation-logloss:0.49001
[133]	validation-logloss:0.48908
[134]	validation-logloss:0.48884
[135]	validation-logloss:0.48901
[136]	validation-logloss:0.48841
[137]	validation-logloss:0.48816
[138]	validation-logloss:0.48754
[139]	validation-logloss:0.48714
[140]	validation-logloss:0.48681
[141]	validation-logloss:0.48670
[142]	validation-logloss:0.48642
[143]	validation-logloss:0.48656
[144]	validation-logloss:0.48673
[145]	validation-logloss:0.48641
[146]	validation-logloss:0.48592
[147]	validation-logloss:0.48546
[148]	validation-logloss:0.48469
[149]	validation-logloss:0.48428
[150]	validation-logloss:0.48414
[151]	validation-logloss:0.48356
[152]	validation-logloss:0.48283
[153]	validation-logloss:0.48234
[154]	validation-logloss:0.48195
[155]	validation-logloss:0.48125
[156]	validation-logloss:0.48085
[157]	validation-logloss:0.48029
[158]	validation-logloss:0.47958
[159]	validation-logloss:0.47920
[160]	validation-logloss:0.47897
[161]	validation-logloss:0.47886
[162]	validation-logloss:0.47833
[163]	validation-logloss:0.47813
[164]	validation-logloss:0.47745
[165]	validation-logloss:0.47702
[166]	validation-logloss:0.47664
[167]	validation-logloss:0.47685
[168]	validation-logloss:0.47658
[169]	validation-logloss:0.47632
[170]	validation-logloss:0.47588
[171]	validation-logloss:0.47559
[172]	validation-logloss:0.47502
[173]	validation-logloss:0.47430
[174]	validation-logloss:0.47373
[175]	validation-logloss:0.47332
[176]	validation-logloss:0.47271
[177]	validation-logloss:0.47235
[178]	validation-logloss:0.47178
[179]	validation-logloss:0.47142
[180]	validation-logloss:0.47102
[181]	validation-logloss:0.47058
[182]	validation-logloss:0.47019
[183]	validation-logloss:0.46960
[184]	validation-logloss:0.46916
[185]	validation-logloss:0.46902
[186]	validation-logloss:0.46922
[187]	validation-logloss:0.46867
[188]	validation-logloss:0.46824
[189]	validation-logloss:0.46823
[190]	validation-logloss:0.46799
[191]	validation-logloss:0.46725
[192]	validation-logloss:0.46711
[193]	validation-logloss:0.46641
[194]	validation-logloss:0.46592
[195]	validation-logloss:0.46595
[196]	validation-logloss:0.46567
[197]	validation-logloss:0.46508
[198]	validation-logloss:0.46506
[199]	validation-logloss:0.46471
[200]	validation-logloss:0.46474
[201]	validation-logloss:0.46439
[202]	validation-logloss:0.46443
[203]	validation-logloss:0.46465
[204]	validation-logloss:0.46457
[205]	validation-logloss:0.46430
[206]	validation-logloss:0.46370
[207]	validation-logloss:0.46320
[208]	validation-logloss:0.46323
[209]	validation-logloss:0.46324
[210]	validation-logloss:0.46298
[211]	validation-logloss:0.46235
[212]	validation-logloss:0.46222
[213]	validation-logloss:0.46255
[214]	validation-logloss:0.46253
[215]	validation-logloss:0.46250
[216]	validation-logloss:0.46228
[217]	validation-logloss:0.46225
[218]	validation-logloss:0.46239
[219]	validation-logloss:0.46213
[220]	validation-logloss:0.46198
[221]	validation-logloss:0.46150
[222]	validation-logloss:0.46125
[223]	validation-logloss:0.46093
[224]	validation-logloss:0.46107
[225]	validation-logloss:0.46096
[226]	validation-logloss:0.46059
[227]	validation-logloss:0.46031
[228]	validation-logloss:0.45996
[229]	validation-logloss:0.45968
[230]	validation-logloss:0.45931
[231]	validation-logloss:0.45914
[232]	validation-logloss:0.45894
[233]	validation-logloss:0.45854
[234]	validation-logloss:0.45814
[235]	validation-logloss:0.45795
[236]	validation-logloss:0.45772
[237]	validation-logloss:0.45759
[238]	validation-logloss:0.45779
[239]	validation-logloss:0.45741
[240]	validation-logloss:0.45722
[241]	validation-logloss:0.45700
[242]	validation-logloss:0.45695
[243]	validation-logloss:0.45677
[244]	validation-logloss:0.45655
[245]	validation-logloss:0.45665
[246]	validation-logloss:0.45626
[247]	validation-logloss:0.45609
[248]	validation-logloss:0.45588
[249]	validation-logloss:0.45593
[250]	validation-logloss:0.45560
[251]	validation-logloss:0.45560
[252]	validation-logloss:0.45526
[253]	validation-logloss:0.45492
[254]	validation-logloss:0.45471
[255]	validation-logloss:0.45513
[256]	validation-logloss:0.45444
[257]	validation-logloss:0.45409
[258]	validation-logloss:0.45404
[259]	validation-logloss:0.45386
[260]	validation-logloss:0.45348
[261]	validation-logloss:0.45331
[262]	validation-logloss:0.45334
[263]	validation-logloss:0.45300
[264]	validation-logloss:0.45260
[265]	validation-logloss:0.45254
[266]	validation-logloss:0.45260
[267]	validation-logloss:0.45230
[268]	validation-logloss:0.45229
[269]	validation-logloss:0.45203
[270]	validation-logloss:0.45196
[271]	validation-logloss:0.45160
[272]	validation-logloss:0.45147
[273]	validation-logloss:0.45195
[274]	validation-logloss:0.45179
[275]	validation-logloss:0.45181
[276]	validation-logloss:0.45134
[277]	validation-logloss:0.45133
[278]	validation-logloss:0.45115
[279]	validation-logloss:0.45065
[280]	validation-logloss:0.45051
[281]	validation-logloss:0.45040
[282]	validation-logloss:0.45023
[283]	validation-logloss:0.44998
[284]	validation-logloss:0.44967
[285]	validation-logloss:0.44962
[286]	validation-logloss:0.44958
[287]	validation-logloss:0.44949
[288]	validation-logloss:0.44933
[289]	validation-logloss:0.44943
[290]	validation-logloss:0.44931
[291]	validation-logloss:0.44948
[292]	validation-logloss:0.44928
[293]	validation-logloss:0.44965
[294]	validation-logloss:0.44963
[295]	validation-logloss:0.44980
[296]	validation-logloss:0.44938
[297]	validation-logloss:0.44944
[298]	validation-logloss:0.44919
[299]	validation-logloss:0.44943

[I 2026-04-25 02:54:58,360] Trial 7 finished with value: 0.8616666666666667 and parameters: {'lambda': 0.745316399991441, 'alpha': 0.008950540393342496, 'max_depth': 8, 'min_child_weight': 1, 'gamma': 7.715364177018861e-08, 'subsample': 0.7678768005463752, 'colsample_bytree': 0.5546338831582989, 'eta': 0.010611776888842527}. Best is trial 6 with value: 0.8696296296296295.

[0]	validation-logloss:0.61072
[1]	validation-logloss:0.54177

[I 2026-04-25 02:54:58,375] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.62539
[1]	validation-logloss:0.56577

[I 2026-04-25 02:54:58,391] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63388
[1]	validation-logloss:0.60629

[I 2026-04-25 02:54:58,423] Trial 10 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63827
[1]	validation-logloss:0.61638

[I 2026-04-25 02:54:58,452] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.62807
[1]	validation-logloss:0.60464

[I 2026-04-25 02:54:58,480] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64085
[1]	validation-logloss:0.62566

[I 2026-04-25 02:54:58,508] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63531
[1]	validation-logloss:0.61591

[I 2026-04-25 02:54:58,537] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63957
[1]	validation-logloss:0.62348

[I 2026-04-25 02:54:58,565] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.59801
[1]	validation-logloss:0.54979

[I 2026-04-25 02:54:58,595] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63034
[1]	validation-logloss:0.59743

[I 2026-04-25 02:54:58,620] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64054
[1]	validation-logloss:0.62522
[2]	validation-logloss:0.61747
[3]	validation-logloss:0.60483
[4]	validation-logloss:0.59610
[5]	validation-logloss:0.58509
[6]	validation-logloss:0.57899
[7]	validation-logloss:0.56771

[I 2026-04-25 02:54:58,659] Trial 18 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.64634
[1]	validation-logloss:0.64300
[2]	validation-logloss:0.63975
[3]	validation-logloss:0.63690
[4]	validation-logloss:0.63446
[5]	validation-logloss:0.63179
[6]	validation-logloss:0.63027
[7]	validation-logloss:0.62716

[I 2026-04-25 02:54:58,699] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.61925
[1]	validation-logloss:0.58663

[I 2026-04-25 02:54:58,730] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64532
[1]	validation-logloss:0.64038
[2]	validation-logloss:0.63778
[3]	validation-logloss:0.63339
[4]	validation-logloss:0.63060
[5]	validation-logloss:0.62711
[6]	validation-logloss:0.62494
[7]	validation-logloss:0.62073

[I 2026-04-25 02:54:58,772] Trial 21 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.64256
[1]	validation-logloss:0.62970

[I 2026-04-25 02:54:58,802] Trial 22 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63778
[1]	validation-logloss:0.61417

[I 2026-04-25 02:54:58,835] Trial 23 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64134
[1]	validation-logloss:0.62975
[2]	validation-logloss:0.62485
[3]	validation-logloss:0.61516
[4]	validation-logloss:0.60899
[5]	validation-logloss:0.60149
[6]	validation-logloss:0.59483
[7]	validation-logloss:0.58628

[I 2026-04-25 02:54:58,876] Trial 24 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.63291
[1]	validation-logloss:0.60323

[I 2026-04-25 02:54:58,904] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63743
[1]	validation-logloss:0.61355

[I 2026-04-25 02:54:58,936] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64318
[1]	validation-logloss:0.63255
[2]	validation-logloss:0.62784
[3]	validation-logloss:0.61916
[4]	validation-logloss:0.61415
[5]	validation-logloss:0.60690
[6]	validation-logloss:0.60179
[7]	validation-logloss:0.59486

[I 2026-04-25 02:54:58,975] Trial 27 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.61684
[1]	validation-logloss:0.55775

[I 2026-04-25 02:54:59,004] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63985
[1]	validation-logloss:0.62136

[I 2026-04-25 02:54:59,033] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64258
[1]	validation-logloss:0.63379

[I 2026-04-25 02:54:59,062] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64543
[1]	validation-logloss:0.63960
[2]	validation-logloss:0.63765
[3]	validation-logloss:0.63219
[4]	validation-logloss:0.62840
[5]	validation-logloss:0.62417
[6]	validation-logloss:0.62180
[7]	validation-logloss:0.61648

[I 2026-04-25 02:54:59,100] Trial 31 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.64561
[1]	validation-logloss:0.64049
[2]	validation-logloss:0.63861
[3]	validation-logloss:0.63374
[4]	validation-logloss:0.63067
[5]	validation-logloss:0.62658
[6]	validation-logloss:0.62355
[7]	validation-logloss:0.61924

[I 2026-04-25 02:54:59,142] Trial 32 pruned. Trial was pruned at iteration 8.

[0]	validation-logloss:0.64024
[1]	validation-logloss:0.62309

[I 2026-04-25 02:54:59,170] Trial 33 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64568
[1]	validation-logloss:0.64238
[2]	validation-logloss:0.64126
[3]	validation-logloss:0.63773
[4]	validation-logloss:0.63596
[5]	validation-logloss:0.63317
[6]	validation-logloss:0.63111
[7]	validation-logloss:0.62796
[8]	validation-logloss:0.62464
[9]	validation-logloss:0.62161
[10]	validation-logloss:0.62028
[11]	validation-logloss:0.61815
[12]	validation-logloss:0.61701
[13]	validation-logloss:0.61462
[14]	validation-logloss:0.61309
[15]	validation-logloss:0.61192
[16]	validation-logloss:0.60905
[17]	validation-logloss:0.60740
[18]	validation-logloss:0.60616
[19]	validation-logloss:0.60506
[20]	validation-logloss:0.60400
[21]	validation-logloss:0.60300
[22]	validation-logloss:0.60035
[23]	validation-logloss:0.59806
[24]	validation-logloss:0.59574
[25]	validation-logloss:0.59488
[26]	validation-logloss:0.59380
[27]	validation-logloss:0.59259
[28]	validation-logloss:0.59040
[29]	validation-logloss:0.58883
[30]	validation-logloss:0.58741
[31]	validation-logloss:0.58525

[I 2026-04-25 02:54:59,269] Trial 34 pruned. Trial was pruned at iteration 32.

[0]	validation-logloss:0.61555
[1]	validation-logloss:0.55401

[I 2026-04-25 02:54:59,302] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.60723
[1]	validation-logloss:0.55746

[I 2026-04-25 02:54:59,329] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63899
[1]	validation-logloss:0.62056

[I 2026-04-25 02:54:59,361] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63588
[1]	validation-logloss:0.61485

[I 2026-04-25 02:54:59,390] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64187
[1]	validation-logloss:0.62987

[I 2026-04-25 02:54:59,420] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64034
[1]	validation-logloss:0.62341

[I 2026-04-25 02:54:59,452] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.61761
[1]	validation-logloss:0.55203

[I 2026-04-25 02:54:59,486] Trial 41 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.61194
[1]	validation-logloss:0.54242

[I 2026-04-25 02:54:59,514] Trial 42 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.62157
[1]	validation-logloss:0.56615

[I 2026-04-25 02:54:59,546] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.59916
[1]	validation-logloss:0.54011

[I 2026-04-25 02:54:59,577] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.61843
[1]	validation-logloss:0.58149

[I 2026-04-25 02:54:59,608] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.64511
[1]	validation-logloss:0.60826

[I 2026-04-25 02:54:59,638] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.61413
[1]	validation-logloss:0.55329

[I 2026-04-25 02:54:59,668] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.61395
[1]	validation-logloss:0.56724

[I 2026-04-25 02:54:59,698] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	validation-logloss:0.63081
[1]	validation-logloss:0.60391

[I 2026-04-25 02:54:59,728] Trial 49 pruned. Trial was pruned at iteration 2.

In [8]:
best_params = study.best_params

final_params = {
    **best_params,
    "objective": "binary:logistic",
    "eval_metric": "logloss",
    "verbosity": 0,
}

In [9]:
dtrain_full = xgb.DMatrix(X_temp, label=y_temp)
dtest = xgb.DMatrix(X_test, label=y_test)

final_model = xgb.train(
    final_params,
    dtrain_full,
    num_boost_round=300
)

In [10]:
y_proba = final_model.predict(dtest)

print("Best Params:", study.best_params)
print("Best Validation AUC:", study.best_value)
print("Test ROC AUC:", roc_auc_score(y_test, y_proba))

Best Params: {'lambda': 4.321228963536233e-07, 'alpha': 0.0002237742348738362, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 1.1195756351090675e-08, 'subsample': 0.561556149437213, 'colsample_bytree': 0.5676139159388394, 'eta': 0.013915542743618298}
Best Validation AUC: 0.8696296296296295
Test ROC AUC: 0.8207407407407407

> The model shows mild overfitting: the validation ROC-AUC is about 0.05 higher than the test ROC-AUC.

## How to Improve Generalization

1. Use cross-validation inside Optuna (recommended)
Use `StratifiedKFold` in the objective so each trial is scored across folds.

```python
from sklearn.model_selection import StratifiedKFold
```

This reduces variance and gives a more stable AUC estimate.

2. Tune `scale_pos_weight`
The dataset is imbalanced, so include class weighting in the search space:

```python
"scale_pos_weight": trial.suggest_float("scale_pos_weight", 1, 5)
```

A practical baseline is:

```python
scale_pos_weight = (number_of_negative_class) / (number_of_positive_class)
```

3. Increase the number of Optuna trials
Try `n_trials=100` (or higher) for a better search over the parameter space.

4. Compare with a strong baseline
Benchmark against a Random Forest model to confirm XGBoost is meaningfully better.